experiment_name: isles_25d_convnext_nnunet_improved_v2_aug_1mm
seed: 42
data:
  csv_path: data/splits/my_dataset_dwi_adc_flair_train_val_test.csv
  root: data/processed/my_dataset_dwi_adc_flair_1mm
  k_slices: 2
  img_size:
  - 256
  - 256
  normalize: fixed_nonzero_zscore
train:
  batch_size: 4
  val_batch_size: 4
  num_workers: 0
  epochs: 100
  lr: 0.0003
  weight_decay: 0.0001
  amp: false
  backbone: convnext_tiny
  pretrained: true
  first_conv_init: repeat
  dec_ch: 256
  deep_sup: true
  stage_dropout_p: 0.1
  decoder_dropout_p: 0.0
  scheduler: cosine
  warmup_epochs: 5
  min_lr: 1.0e-06
  sampler: pos_oversample
  pos_slice_weight: 50.0
  neg_slice_weight: 1.0
  augment: true
  p_flip: 0.5
  aug_rotation: 20.0
  aug_scale_range:
  - 0.85
  - 1.15
  aug_gamma_range:
  - 0.6
  - 1.5
  aug_noise_std: 0.03
  aug_intensity_scale_range:
  - 0.85
  - 1.15
  aug_intensity_shift_std: 0.1
  aug_blur_p: 0.3
  aug_blur_sigma_range:
  - 0.5
  - 1.5
  aug_bias_field_p: 0.3
  aug_bias_field_std: 0.3
  loss: dice_ohem_bce
  ohem_neg_fraction: 0.05
  ohem_min_neg: 2048
  ohem_pos_weight: 1.0
  ohem_neg_weight: 1.0
  ema: true
  ema_decay: 0.9998
  max_train_batches: 500
log:
  out_dir: results/isles_25d_convnext_nnunet_improved
